import { useEffect, useMemo, useState } from 'react';
import { Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Card, Choice, PrimaryButton, SearchInput, SectionTitle } from '@/components/ui';
import ExactSystemComponentSelector from '@/components/ExactSystemComponentSelector';
import { getScannerOptions, getSystemRequirements, runExactSystemQuickCheck, searchComponents, searchDevices, searchScanners, type ExactComponentSelection, type QuickCheckItem, type QuickCheckResult, type SystemRequirement } from '@/lib/quickcheck';

const regions = ['Full body', 'Head', 'Spine', 'Chest', 'Abdomen', 'Pelvis', 'Extremity'];
const strengths = [1.5, 3];

function label(item: QuickCheckItem) { const name = item.model_name || item.name || 'Unknown model'; const number = item.model_number || item.model || item.catalog_number; return number ? `${name} • ${number}` : String(name); }
function isDual(requirements: SystemRequirement[]) { return requirements.some((x) => x.status === 'current' || x.status === 'legacy' ? x.system_type === 'dual_chamber' : false); }

export default function QuickCheckV11() {
  const [step, setStep] = useState(1); const [deviceSearch, setDeviceSearch] = useState(''); const [componentSearch, setComponentSearch] = useState('');
  const [devices, setDevices] = useState<QuickCheckItem[]>([]); const [components, setComponents] = useState<QuickCheckItem[]>([]); const [requirements, setRequirements] = useState<SystemRequirement[]>([]);
  const [scannerOptions, setScannerOptions] = useState<QuickCheckItem[]>([]); const [scanners, setScanners] = useState<QuickCheckItem[]>([]);
  const [device, setDevice] = useState<QuickCheckItem | null>(null); const [selections, setSelections] = useState<ExactComponentSelection[]>([]);
  const [scanner, setScanner] = useState<QuickCheckItem | null>(null); const [strength, setStrength] = useState<number | null>(null); const [region, setRegion] = useState('Full body');
  const [loading, setLoading] = useState(false); const [result, setResult] = useState<QuickCheckResult | null>(null); const [error, setError] = useState('');

  useEffect(() => { getScannerOptions().then(setScannerOptions).catch(() => setScannerOptions([])); }, []);
  useEffect(() => { const t = setTimeout(() => searchDevices(deviceSearch).then(setDevices).catch(() => setDevices([])), 250); return () => clearTimeout(t); }, [deviceSearch]);
  useEffect(() => { if (!device) { setComponents([]); setRequirements([]); return; } getSystemRequirements(device.id).then(setRequirements).catch(() => setRequirements([])); const t = setTimeout(() => searchComponents(device.id, componentSearch).then(setComponents).catch(() => setComponents([])), 250); return () => clearTimeout(t); }, [device, componentSearch]);

  const manufacturers = useMemo(() => { const seen = new Set<string>(); return scannerOptions.filter((x) => { const id = String(x.manufacturer_id ?? x.id); if (seen.has(id)) return false; seen.add(id); return true; }); }, [scannerOptions]);
  const dual = isDual(requirements); const requiredLeads = requirements.find((x) => x.status === 'current')?.required_lead_count ?? (dual ? 2 : 1);
  const generatorSelected = selections.some((x) => x.slot === 'generator');
  const leadSelections = selections.filter((x) => x.slot !== 'generator');
  const componentSlotsComplete = generatorSelected && leadSelections.length === requiredLeads;

  function selectComponent(slot: string, item: QuickCheckItem) { setSelections((current) => { const rest = current.filter((x) => x.slot !== slot); return [...rest, { slot, component_id: item.id }]; }); }
  async function chooseManufacturer(item: QuickCheckItem) { try { setScanner(null); setScanners(await searchScanners(String(item.manufacturer_id ?? item.id))); } catch { setScanners([]); } }
  async function check() {
    if (!device || !scanner || !strength || !componentSlotsComplete) return; setLoading(true); setError('');
    try { const response = await runExactSystemQuickCheck({ device_id: device.id, components: selections, scanner_model_id: scanner.id, scanner_strength_t: strength, scan_region: region }); setResult(response); setStep(5); }
    catch (e) { setError(e instanceof Error ? e.message : 'Unable to complete the safety check.'); } finally { setLoading(false); }
  }
  function reset() { setStep(1); setDevice(null); setSelections([]); setScanner(null); setStrength(null); setResult(null); setError(''); setDeviceSearch(''); setComponentSearch(''); setScanners([]); setRequirements([]); }

  if (result) return <Result result={result} onAgain={reset} />;
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>MRI SAFETY</Text><Text style={styles.title}>QuickCheck</Text></View><Pressable onPress={() => router.push('/(app)/settings')} style={styles.settings}><Text style={styles.settingsText}>⚙</Text></Pressable></View>
    <View style={styles.progress}><View style={[styles.progressFill, { width: `${step * 20}%` }]} /></View><Text style={styles.step}>STEP {step} OF 5</Text>
    {step === 1 && <Card><SectionTitle title="Identify the implant" subtitle="Select the exact manufacturer model or catalog number."/><SearchInput value={deviceSearch} onChangeText={setDeviceSearch} placeholder="Search implant or model…" autoFocus />{devices.slice(0, 8).map((item) => <Choice key={item.id} label={label(item)} selected={device?.id === item.id} onPress={() => { setDevice(item); setSelections([]); setStep(2); }} />)}</Card>}
    {step === 2 && <Card><SectionTitle title="Build the exact implanted system" subtitle="Every implanted component must be identified. Dual-chamber systems use separate atrial and ventricular slots."/><ExactSystemComponentSelector device={device!} components={components} search={componentSearch} onSearchChange={setComponentSearch} selections={selections} onSelect={selectComponent} systemType={dual ? 'dual_chamber' : 'single_chamber'} requiredLeadCount={requiredLeads}/><View style={styles.selectionSummary}><Text style={styles.selectionSummaryTitle}>{dual ? `${leadSelections.length} of 2 leads selected` : `${leadSelections.length} of 1 lead selected`}</Text><Text style={styles.selectionSummaryText}>The same exact lead model may be selected in both lead slots. It will remain a distinct slot selection, not an inferred duplicate component.</Text></View><PrimaryButton label="CONTINUE" disabled={!componentSlotsComplete} onPress={() => setStep(3)}/></Card>}
    {step === 3 && <Card><SectionTitle title="Select scanner" subtitle="Choose the actual scanner manufacturer and model."/><Text style={styles.subheading}>MANUFACTURER</Text>{manufacturers.slice(0, 10).map((item) => <Choice key={String(item.manufacturer_id ?? item.id)} label={String(item.manufacturer_name ?? item.name ?? 'Manufacturer')} selected={String(scanner?.manufacturer_id) === String(item.manufacturer_id ?? item.id)} onPress={() => chooseManufacturer(item)}/>) }<Text style={styles.subheading}>SCANNER MODEL</Text>{scanners.slice(0, 10).map((item) => <Choice key={item.id} label={label(item)} selected={scanner?.id === item.id} onPress={() => setScanner(item)}/>) }<PrimaryButton label="CONTINUE" disabled={!scanner} onPress={() => setStep(4)}/></Card>}
    {step === 4 && <Card><SectionTitle title="Scan parameters" subtitle="Field strength and scan region are evaluated against the current labeling."/><Text style={styles.subheading}>FIELD STRENGTH</Text><View style={styles.row}>{strengths.map((value) => <Pressable key={value} onPress={() => setStrength(value)} style={[styles.strength, strength === value && styles.strengthSelected]}><Text style={[styles.strengthValue, strength === value && styles.strengthTextSelected]}>{value}T</Text></Pressable>)}</View><Text style={styles.subheading}>SCAN REGION</Text>{regions.map((item) => <Choice key={item} label={item} selected={region === item} onPress={() => setRegion(item)}/>) }{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label="CHECK MRI SAFETY" loading={loading} disabled={!strength} onPress={check}/></Card>}
    <View style={styles.footer}><Text style={styles.footerText}>Manufacturer labeling is the primary authority. CONDITIONAL is not clearance. UNKNOWN never means safe.</Text></View>
  </ScrollView>;
}

function Result({ result, onAgain }: { result: QuickCheckResult; onAgain: () => void }) { const tone = result.status === 'safe' ? '#166534' : result.status === 'conditional' ? '#92400e' : '#991b1b'; const components = Array.isArray(result.components) ? result.components : []; return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>MRI SAFETY RESULT</Text><Text style={styles.title}>QuickCheck</Text></View><Pressable onPress={onAgain} style={styles.newButton}><Text style={styles.newButtonText}>NEW</Text></Pressable></View><View style={[styles.resultHero,{borderColor:tone}]}><Text style={[styles.resultStatus,{color:tone}]}>{result.display_status || result.status.toUpperCase()}</Text><Text style={styles.resultHeadline}>{result.safe_to_scan ? 'SAFE TO SCAN' : 'NOT CLEARED TO SCAN'}</Text><Text style={styles.resultDecision}>{result.decision || result.next_action || 'Review the current manufacturer labeling before proceeding.'}</Text></View><Card><SectionTitle title="Checked configuration"/><Info label="Implant" value={displayObject(result.device)}/>{components.map((entry,index)=><View key={String(entry.slot ?? index)} style={styles.componentResult}><Text style={styles.infoLabel}>{slotTitle(String(entry.slot ?? 'component'))}</Text><Text style={styles.infoValue}>{displayObject((entry.component as Record<string,unknown>) ?? entry)}</Text></View>)}<Info label="Scanner" value={displayObject(result.scanner)}/><Info label="Field strength" value={String(result.scanner?.field_strength_t ?? 'Not verified') + (result.scanner?.field_strength_t ? 'T' : '')}/></Card><Card><SectionTitle title="Safety gate"/><Text style={[styles.gate,{color:tone}]}>{result.safe_to_scan ? 'SAFE TO SCAN' : 'NOT CLEARED'}</Text><Text style={styles.footerText}>{result.requires_review ? 'Review required before proceeding.' : 'Use current manufacturer labeling and facility protocol.'}</Text></Card>{getSource(result) ? <Pressable style={styles.sourceButton} onPress={() => Linking.openURL(getSource(result)!.url).catch(() => Alert.alert('Unable to open source'))}><Text style={styles.sourceButtonText}>OPEN MANUFACTURER SOURCE</Text></Pressable> : null}<PrimaryButton label="START NEW CHECK" onPress={onAgain}/></ScrollView>; }
function slotTitle(slot: string) { if (slot === 'generator') return 'Generator / Device'; if (slot === 'lead_1') return 'Atrial Lead'; if (slot === 'lead_2') return 'Ventricular Lead'; return slot; }
function displayObject(value?: Record<string, unknown> | null) { if (!value) return 'Not identified'; const name = value.model_name ?? value.name ?? value.model ?? 'Selected'; const number = value.model_number ?? value.model; return number && number !== name ? `${name} • ${number}` : String(name); }
function getSource(result: QuickCheckResult) { const candidates=[result.condition,result.device,result as Record<string,unknown>]; for(const c of candidates){ if(!c) continue; const url=c.source_url ?? c.url ?? c.source_uri; if(typeof url==='string') return {url}; } return null; }
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text selectable style={styles.infoValue}>{value}</Text></View>}

const styles=StyleSheet.create({content:{flexGrow:1,padding:20,paddingBottom:40,gap:14,backgroundColor:'#f7f9fc'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingTop:8},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:2,color:'#667085'},title:{fontSize:32,fontWeight:'900',color:'#101828',marginTop:3},settings:{width:42,height:42,borderRadius:12,backgroundColor:'#fff',borderWidth:1,borderColor:'#e4e7ec',alignItems:'center',justifyContent:'center'},settingsText:{fontSize:19},newButton:{paddingHorizontal:15,paddingVertical:10,borderRadius:10,backgroundColor:'#111827'},newButtonText:{color:'#fff',fontSize:12,fontWeight:'900'},progress:{height:5,backgroundColor:'#e4e7ec',borderRadius:5,overflow:'hidden',marginTop:4},progressFill:{height:5,backgroundColor:'#175cd3'},step:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#667085'},selectionSummary:{borderTopWidth:1,borderTopColor:'#eaecf0',paddingTop:12,gap:4},selectionSummaryTitle:{fontSize:14,fontWeight:'900',color:'#101828'},selectionSummaryText:{fontSize:12,lineHeight:18,color:'#667085'},subheading:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#667085',marginTop:5},row:{flexDirection:'row',gap:10},strength:{flex:1,height:64,borderRadius:14,borderWidth:1,borderColor:'#d9dee7',alignItems:'center',justifyContent:'center',backgroundColor:'#fff'},strengthSelected:{borderColor:'#175cd3',backgroundColor:'#eff6ff'},strengthValue:{fontSize:20,fontWeight:'900',color:'#344054'},strengthTextSelected:{color:'#175cd3'},error:{color:'#b42318',fontSize:13,lineHeight:19},footer:{padding:4},footerText:{fontSize:12,lineHeight:18,color:'#667085'},resultHero:{backgroundColor:'#fff',borderWidth:2,borderRadius:20,padding:22,gap:8},resultStatus:{fontSize:24,fontWeight:'900'},resultHeadline:{fontSize:19,fontWeight:'900',color:'#101828'},resultDecision:{fontSize:15,lineHeight:22,color:'#344054'},componentResult:{paddingVertical:5,gap:2},info:{paddingVertical:5,gap:2},infoLabel:{fontSize:11,fontWeight:'800',color:'#667085',textTransform:'uppercase',letterSpacing:.5},infoValue:{fontSize:15,fontWeight:'700',color:'#101828'},gate:{fontSize:24,fontWeight:'900'},sourceButton:{padding:16,borderRadius:12,backgroundColor:'#111827',alignItems:'center'},sourceButtonText:{color:'#fff',fontSize:12,fontWeight:'900',letterSpacing:.7}});
