import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Card, PrimaryButton, SectionTitle } from '@/components/ui';
import { deleteScannerProfile, listScannerProfiles, saveScannerProfile, type ScannerProfile } from '@/lib/quickcheck';

const manufacturers = ['Siemens Healthineers','GE HealthCare','Philips','Canon Medical Systems','United Imaging'];
const strengths = [1.5, 3];

export default function ScannerProfiles() {
  const [profiles,setProfiles]=useState<ScannerProfile[]>([]); const [manufacturer,setManufacturer]=useState(manufacturers[0]); const [model,setModel]=useState(''); const [nickname,setNickname]=useState(''); const [strength,setStrength]=useState(1.5); const [makeDefault,setMakeDefault]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  async function load(){ try{setProfiles(await listScannerProfiles());}catch(e){setError(e instanceof Error?e.message:'Unable to load scanners.');} }
  useEffect(()=>{load();},[]);
  async function save(){ if(!model.trim()) return; setSaving(true); setError(''); try{await saveScannerProfile({manufacturer,model:model.trim(),field_strength_t:strength,nickname:nickname.trim(),is_default:makeDefault}); setModel(''); setNickname(''); setMakeDefault(false); await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save scanner.');}finally{setSaving(false);} }
  async function remove(id:string){ Alert.alert('Remove scanner','Remove this saved scanner profile?', [{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:async()=>{try{await deleteScannerProfile(id); await load();}catch(e){Alert.alert('Scanner profile',e instanceof Error?e.message:'Unable to remove scanner.');}}}]); }
  async function makeDefaultProfile(p:ScannerProfile){ try{await saveScannerProfile({id:p.id,manufacturer:p.manufacturer,model:p.model,field_strength_t:Number(p.field_strength_t),nickname:p.nickname ?? '',is_default:true}); await load();}catch(e){Alert.alert('Scanner profile',e instanceof Error?e.message:'Unable to set default.');} }
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><View><Text style={styles.eyebrow}>MRI SCANNERS</Text><Text style={styles.title}>Saved scanners</Text></View><View style={{width:52}}/></View>
    <Card><SectionTitle title="Your scanner profiles" subtitle="Save the exact make/model you use. Compatibility still evaluates against the generic 1.5T or 3T manufacturer entry and implant labeling."/>{profiles.length===0?<Text style={styles.muted}>No scanners saved yet.</Text>:profiles.map(p=><View key={p.id} style={styles.profile}><View style={{flex:1}}><View style={styles.profileTitleRow}><Text style={styles.profileTitle}>{p.nickname || p.model}</Text>{p.is_default?<Text style={styles.defaultBadge}>DEFAULT</Text>:null}</View><Text style={styles.profileMeta}>{p.manufacturer} • {p.model} • {Number(p.field_strength_t)}T</Text><Text style={styles.profileBasis}>Compatibility basis: {p.generic_model || `${Number(p.field_strength_t)}T generic`}</Text></View><View style={styles.actions}>{!p.is_default?<Pressable onPress={()=>makeDefaultProfile(p)}><Text style={styles.link}>Default</Text></Pressable>:null}<Pressable onPress={()=>remove(p.id)}><Text style={styles.remove}>Remove</Text></Pressable></View></View>)}</Card>
    <Card><SectionTitle title="Add scanner" subtitle="Use the name shown on the scanner/site inventory, for example MAGNETOM Vida or SIGNA Artist."/><Text style={styles.label}>MANUFACTURER</Text><View style={styles.wrap}>{manufacturers.map(x=><Pressable key={x} onPress={()=>setManufacturer(x)} style={[styles.chip,manufacturer===x&&styles.chipSelected]}><Text style={[styles.chipText,manufacturer===x&&styles.chipTextSelected]}>{x}</Text></Pressable>)}</View><Text style={styles.label}>SCANNER MODEL</Text><TextInput value={model} onChangeText={setModel} placeholder="e.g. MAGNETOM Vida" style={styles.input}/><Text style={styles.label}>NICKNAME (OPTIONAL)</Text><TextInput value={nickname} onChangeText={setNickname} placeholder="e.g. Southlake MRI 1" style={styles.input}/><Text style={styles.label}>FIELD STRENGTH</Text><View style={styles.row}>{strengths.map(x=><Pressable key={x} onPress={()=>setStrength(x)} style={[styles.strength,strength===x&&styles.strengthSelected]}><Text style={[styles.strengthText,strength===x&&styles.strengthTextSelected]}>{x}T</Text></Pressable>)}</View><Pressable onPress={()=>setMakeDefault(v=>!v)} style={styles.defaultRow}><View style={[styles.checkbox,makeDefault&&styles.checkboxSelected]}><Text style={styles.check}>{makeDefault?'✓':''}</Text></View><Text style={styles.defaultText}>Use as my default scanner</Text></Pressable>{error?<Text style={styles.error}>{error}</Text>:null}<PrimaryButton label="SAVE SCANNER" loading={saving} disabled={!model.trim()} onPress={save}/></Card>
    <Text style={styles.footer}>Saved scanner make/model is workflow context. MRI clearance is determined by exact implant/system labeling, selected field strength, scan region, and all applicable manufacturer conditions.</Text>
  </ScrollView>;
}

const styles=StyleSheet.create({content:{flexGrow:1,padding:20,paddingBottom:42,gap:14,backgroundColor:'#f5f7fb'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingTop:8},back:{fontSize:16,fontWeight:'800',color:'#175cd3'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#667085',textAlign:'center'},title:{fontSize:25,fontWeight:'900',color:'#101828'},muted:{fontSize:13,color:'#667085'},profile:{flexDirection:'row',gap:12,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#eaecf0'},profileTitleRow:{flexDirection:'row',alignItems:'center',gap:8},profileTitle:{fontSize:16,fontWeight:'900',color:'#101828'},defaultBadge:{fontSize:9,fontWeight:'900',color:'#166534',backgroundColor:'#ecfdf3',paddingHorizontal:7,paddingVertical:4,borderRadius:7},profileMeta:{fontSize:13,color:'#475467',marginTop:3},profileBasis:{fontSize:11,color:'#667085',marginTop:4},actions:{alignItems:'flex-end',justifyContent:'center',gap:8},link:{fontSize:12,fontWeight:'900',color:'#175cd3'},remove:{fontSize:12,fontWeight:'900',color:'#b42318'},label:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#667085',marginTop:4},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:10,paddingVertical:9,borderRadius:10,borderWidth:1,borderColor:'#d0d5dd',backgroundColor:'#fff'},chipSelected:{borderColor:'#175cd3',backgroundColor:'#eff6ff'},chipText:{fontSize:12,fontWeight:'800',color:'#344054'},chipTextSelected:{color:'#175cd3'},input:{minHeight:50,borderRadius:12,borderWidth:1,borderColor:'#d0d5dd',backgroundColor:'#fff',paddingHorizontal:14,fontSize:15,color:'#101828'},row:{flexDirection:'row',gap:10},strength:{flex:1,height:58,borderRadius:13,borderWidth:1,borderColor:'#d0d5dd',alignItems:'center',justifyContent:'center',backgroundColor:'#fff'},strengthSelected:{borderColor:'#175cd3',backgroundColor:'#eff6ff'},strengthText:{fontSize:19,fontWeight:'900',color:'#344054'},strengthTextSelected:{color:'#175cd3'},defaultRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:4},checkbox:{width:24,height:24,borderRadius:7,borderWidth:2,borderColor:'#98a2b3',alignItems:'center',justifyContent:'center'},checkboxSelected:{borderColor:'#175cd3',backgroundColor:'#175cd3'},check:{color:'#fff',fontWeight:'900'},defaultText:{fontSize:14,fontWeight:'800',color:'#344054'},error:{fontSize:13,lineHeight:18,color:'#b42318'},footer:{fontSize:12,lineHeight:18,color:'#667085',paddingHorizontal:3}});