import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { Card, SectionTitle } from '@/components/ui';

type Profile = { role?: string | null; email?: string | null; [key: string]: unknown };
type CatalogItem = { entity_type: string; entity_id: string; manufacturer_name?: string|null; model_name?: string|null; model_number?: string|null; device_type?: string|null; labeling_status?: string|null; component_type?: string|null; component_alias?: string|null; source_title?: string|null; source_url?: string|null; source_authority?: string|null; current_for_model?: boolean|null; verified_by?: string|null; verification_notes?: string|null; active?: boolean };
type Overview = { devices_total:number; devices_verified:number; devices_unverified:number; components_total:number; sources_total:number; sources_current:number; sources_verified:number };
type Check = { id:string; result?:Record<string,any>|null; status?:string|null; created_at:string; scanner_strength_t?:number|null; scan_region?:string|null };
const STAFF_ROLES = new Set(['mrso','supervisor','admin']);

export default function Verification() {
  const [profile,setProfile]=useState<Profile|null>(null); const [items,setItems]=useState<CatalogItem[]>([]); const [checks,setChecks]=useState<Check[]>([]); const [overview,setOverview]=useState<Overview|null>(null); const [selected,setSelected]=useState<CatalogItem|null>(null); const [query,setQuery]=useState(''); const [reason,setReason]=useState(''); const [notes,setNotes]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async()=>{setError('');const {data:p,error:pe}=await supabase.rpc('quickcheck_get_profile');if(pe){setError(pe.message);setLoading(false);return;}const raw=Array.isArray(p)?p[0]:p;setProfile(raw??null);const role=String(raw?.role??'').toLowerCase();if(!STAFF_ROLES.has(role)){setLoading(false);return;}const [o,c,h]=await Promise.all([supabase.rpc('quickcheck_staff_catalog_overview'),supabase.rpc('quickcheck_staff_search_catalog',{p_search:query}),supabase.from('scanner_checks').select('id,result,status,created_at,scanner_strength_t,scan_region').order('created_at',{ascending:false}).limit(50)]);if(o.error) setError(o.error.message); else setOverview((o.data??null) as Overview);if(c.error) setError(c.error.message); else setItems((c.data??[]) as CatalogItem[]);if(h.error) setError(h.error.message); else setChecks((h.data??[]) as Check[]);setLoading(false);},[query]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  async function refresh(){setRefreshing(true);await load();setRefreshing(false);}
  function choose(item:CatalogItem){setSelected(item);setReason('');setNotes(item.verification_notes??'');}
  async function setVerification(verified:boolean){if(!selected)return;if(reason.trim().length<3){Alert.alert('Reason required','Enter why this catalog record is being verified or returned to unverified status.');return;}setSaving(true);const {error:e}=await supabase.rpc('quickcheck_staff_set_verification',{p_entity_type:selected.entity_type,p_entity_id:selected.entity_id,p_verified:verified,p_reason:reason.trim(),p_verified_by:String(profile?.role??'staff-review'),p_verification_notes:notes.trim()||null});setSaving(false);if(e){Alert.alert('Unable to save',e.message);return;}Alert.alert(verified?'Record verified':'Record returned to review',verified?'The record is now marked verified.':'The record is no longer verified and will require review.');setSelected(null);await load();}
  if(loading)return <View style={styles.center}><ActivityIndicator/></View>;const role=String(profile?.role??'').toLowerCase();const isStaff=STAFF_ROLES.has(role);
  return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.title}>Verification Center</Text><View style={{width:55}}/></View>
    <View style={styles.banner}><Text style={styles.kicker}>STAFF ACCESS</Text><Text style={styles.bannerTitle}>{isStaff?'Clinical catalog verification':'Technologist access'}</Text><Text style={styles.bannerBody}>{isStaff?'Review manufacturer labeling, source posture, and verification history. Every change requires a reason and is audit logged.':'Verification tools are restricted to MRSO, supervisor, and administrator roles.'}</Text></View>
    {error?<Card><Text style={styles.error}>{error}</Text></Card>:null}
    {!isStaff?<Card><SectionTitle title="Access restricted"/><Text style={styles.body}>Your current role is {role||'technologist'}. Catalog verification is not available to this account.</Text><Pressable style={styles.primary} onPress={()=>router.replace('/(app)/dashboard')}><Text style={styles.primaryText}>RETURN TO DASHBOARD</Text></Pressable></Card>:<>
      {overview?<View style={styles.stats}>{[[overview.devices_verified,'VERIFIED DEVICES'],[overview.devices_unverified,'DEVICES TO REVIEW'],[overview.sources_current,'CURRENT SOURCES'],[overview.sources_verified,'VERIFIED SOURCES']].map(([v,l])=><View style={styles.stat} key={String(l)}><Text style={styles.statValue}>{String(v)}</Text><Text style={styles.statLabel}>{String(l)}</Text></View>)}</View>:null}
      <Card><SectionTitle title="Catalog" subtitle="Search exact device or component records before changing verification status."/><TextInput value={query} onChangeText={setQuery} placeholder="Search manufacturer, model, lead..." placeholderTextColor="#98a2b3" style={styles.search}/>{items.length===0?<Text style={styles.body}>No catalog records match this search.</Text>:items.map(item=><Pressable key={`${item.entity_type}-${item.entity_id}`} onPress={()=>choose(item)} style={styles.catalogRow}><View style={[styles.statusDot,{backgroundColor:item.labeling_status==='verified'?'#039855':'#f79009'}]}/><View style={styles.rowCopy}><Text style={styles.rowTitle}>{item.manufacturer_name||'Manufacturer'} • {item.model_name||item.model_number||'Component'}</Text><Text style={styles.rowMeta}>{item.entity_type.toUpperCase()} • {item.model_number||item.component_alias||''}</Text><Text style={styles.rowMeta}>{item.labeling_status==='verified'?'VERIFIED':'REVIEW REQUIRED'} {item.source_title?`• ${item.source_title}`:'• NO SOURCE SELECTED'}</Text></View></Pressable>)}</Card>
      {selected?<Card><SectionTitle title="Verification review" subtitle="Review the source and exact identification before changing status."/><View style={styles.detail}><Text style={styles.detailLabel}>RECORD</Text><Text style={styles.detailValue}>{selected.manufacturer_name||'Manufacturer'} {selected.model_name||selected.model_number||''}</Text><Text style={styles.detailLabel}>TYPE</Text><Text style={styles.detailValue}>{selected.entity_type}{selected.component_type?` • ${selected.component_type}`:''}</Text><Text style={styles.detailLabel}>CURRENT STATUS</Text><Text style={styles.detailValue}>{String(selected.labeling_status||'unverified').toUpperCase()}</Text><Text style={styles.detailLabel}>SOURCE</Text><Text style={styles.detailValue}>{selected.source_title||'No current source linked'}</Text><Text style={styles.detailMeta}>{selected.source_authority||'Source authority not recorded'} {selected.current_for_model?'• CURRENT':''}</Text>{selected.source_url?<Pressable onPress={()=>Alert.alert('Manufacturer source',selected.source_url||'')}><Text style={styles.link}>Open source URL</Text></Pressable>:null}<Text style={styles.detailLabel}>VERIFICATION NOTES</Text><TextInput value={notes} onChangeText={setNotes} multiline placeholder="Document what was reviewed..." placeholderTextColor="#98a2b3" style={styles.notes}/><Text style={styles.detailLabel}>REQUIRED REASON</Text><TextInput value={reason} onChangeText={setReason} multiline placeholder="Why are you verifying or un-verifying this record?" placeholderTextColor="#98a2b3" style={styles.notes}/><View style={styles.actions}><Pressable disabled={saving} style={[styles.action,styles.verify]} onPress={()=>setVerification(true)}><Text style={styles.actionText}>{saving?'SAVING...':'VERIFY RECORD'}</Text></Pressable><Pressable disabled={saving} style={[styles.action,styles.unverify]} onPress={()=>setVerification(false)}><Text style={styles.actionTextDark}>RETURN TO REVIEW</Text></Pressable></View><Pressable onPress={()=>setSelected(null)}><Text style={styles.cancel}>Cancel</Text></Pressable></View></Card>:null}
      <Card><SectionTitle title="Audit posture"/><Text style={styles.body}>Verification changes are restricted to staff roles, require a reason, preserve the prior record state, and write an audit entry. Manufacturer labeling is the primary authority.</Text><Text style={styles.note}>Verification means source/labeling reviewed against manufacturer documentation. It is not independent clinical validation and never overrides current manufacturer labeling.</Text></Card>
      <Card><SectionTitle title="Recent QuickCheck oversight" subtitle="Recent activity remains visible to authorized staff."/>{checks.length===0?<Text style={styles.body}>No QuickCheck records yet.</Text>:checks.slice(0,10).map(item=>{const r=item.result??{};return <View key={item.id} style={styles.row}><View style={styles.badge}><Text style={styles.badgeText}>{String(r.display_status??r.status??item.status??'UNKNOWN').toUpperCase()}</Text></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{String(r.device?.model??r.device?.model_name??'Implant check')}</Text><Text style={styles.rowMeta}>{item.scanner_strength_t?`${item.scanner_strength_t}T`:'Field'} • {item.scan_region||'Region'} • {new Date(item.created_at).toLocaleString()}</Text></View></View>})}</Card>
    </>}
  </ScrollView>;
}
const styles=StyleSheet.create({content:{flexGrow:1,padding:20,paddingBottom:40,gap:14,backgroundColor:'#f7f9fc'},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingTop:8,paddingBottom:6},back:{fontSize:16,fontWeight:'800',color:'#175cd3'},title:{fontSize:22,fontWeight:'900',color:'#101828'},banner:{borderRadius:20,backgroundColor:'#111827',padding:20,gap:5},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#98a2b3'},bannerTitle:{fontSize:20,fontWeight:'900',color:'#fff'},bannerBody:{fontSize:13,lineHeight:20,color:'#d0d5dd'},stats:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{width:'48%',backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:'#e4e7ec',padding:14},statValue:{fontSize:23,fontWeight:'900',color:'#101828'},statLabel:{fontSize:8,fontWeight:'900',letterSpacing:1,color:'#667085',marginTop:3},body:{fontSize:14,lineHeight:21,color:'#475467'},error:{fontSize:13,lineHeight:20,color:'#b42318'},search:{borderWidth:1,borderColor:'#d0d5dd',borderRadius:12,padding:12,fontSize:14,color:'#101828',backgroundColor:'#fff',marginBottom:10},catalogRow:{flexDirection:'row',gap:10,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#f2f4f7'},statusDot:{width:10,height:10,borderRadius:5,marginTop:5},rowCopy:{flex:1},rowTitle:{fontSize:14,fontWeight:'800',color:'#101828'},rowMeta:{fontSize:11,color:'#667085',marginTop:2},detail:{gap:5},detailLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#667085',marginTop:7},detailValue:{fontSize:14,fontWeight:'700',color:'#101828'},detailMeta:{fontSize:11,color:'#667085'},link:{fontSize:13,fontWeight:'800',color:'#175cd3',marginTop:5},notes:{minHeight:80,borderWidth:1,borderColor:'#d0d5dd',borderRadius:12,padding:12,fontSize:13,color:'#101828',backgroundColor:'#fff',textAlignVertical:'top'},actions:{flexDirection:'row',gap:10,marginTop:8},action:{flex:1,minHeight:48,borderRadius:12,alignItems:'center',justifyContent:'center'},verify:{backgroundColor:'#039855'},unverify:{backgroundColor:'#fef3f2',borderWidth:1,borderColor:'#fecdca'},actionText:{fontSize:11,fontWeight:'900',color:'#fff'},actionTextDark:{fontSize:11,fontWeight:'900',color:'#b42318'},cancel:{textAlign:'center',fontSize:13,fontWeight:'800',color:'#667085',padding:8},primary:{marginTop:15,minHeight:50,borderRadius:13,backgroundColor:'#175cd3',alignItems:'center',justifyContent:'center'},primaryText:{fontSize:12,fontWeight:'900',color:'#fff'},note:{fontSize:12,lineHeight:18,color:'#667085',marginTop:12},badge:{minWidth:78,paddingHorizontal:8,paddingVertical:7,borderRadius:8,backgroundColor:'#f2f4f7',alignItems:'center'},badgeText:{fontSize:9,fontWeight:'900',color:'#344054'},row:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#f2f4f7'}});