import type { ComponentProps, PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

export const palette = { ink:'#0b1220', muted:'#667085', line:'#e5e9f0', surface:'#ffffff', canvas:'#f3f6fa', blue:'#1769e0', blueSoft:'#eef5ff', green:'#157347', greenSoft:'#edf9f2', amber:'#9a6700', amberSoft:'#fff8e6', red:'#b42318', redSoft:'#fff1f0' } as const;
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function SectionTitle({ title, subtitle }: { title: string; subtitle?: string }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{subtitle ? <Text style={styles.sectionSubtitle}>{subtitle}</Text> : null}</View>; }
export function SearchInput(props: ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor="#8b95a7" style={[styles.input, props.style]} />; }
export function Choice({ label, selected, onPress, disabled = false }: { label: string; selected?: boolean; onPress: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[styles.choice, selected && styles.choiceSelected, disabled && styles.disabled, pressed && !disabled && styles.pressed]}><Text style={[styles.choiceText, selected && styles.choiceTextSelected]}>{label}</Text><View style={[styles.radio, selected && styles.radioSelected]}>{selected ? <View style={styles.radioDot} /> : null}</View></Pressable>; }
export function PrimaryButton({ label, onPress, loading, disabled }: { label: string; onPress: () => void; loading?: boolean; disabled?: boolean }) { return <Pressable disabled={disabled || loading} onPress={onPress} style={({pressed})=>[styles.primary, (disabled || loading) && styles.primaryDisabled, pressed && !(disabled||loading) && styles.primaryPressed]}>{loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>{label}</Text>}</Pressable>; }
const styles=StyleSheet.create({card:{backgroundColor:palette.surface,borderRadius:22,padding:20,gap:14,borderWidth:1,borderColor:palette.line,shadowColor:'#0b1220',shadowOpacity:.05,shadowRadius:16,shadowOffset:{width:0,height:5},elevation:2},section:{gap:5},sectionTitle:{fontSize:19,fontWeight:'900',letterSpacing:-.25,color:palette.ink},sectionSubtitle:{fontSize:13,lineHeight:20,color:palette.muted},input:{minHeight:52,backgroundColor:'#f9fbfd',borderWidth:1,borderColor:'#d8dee8',borderRadius:15,paddingHorizontal:16,paddingVertical:13,fontSize:16,color:palette.ink},choice:{minHeight:58,borderWidth:1,borderColor:'#dce2ea',borderRadius:15,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:palette.surface},choiceSelected:{borderColor:palette.blue,backgroundColor:palette.blueSoft},choiceText:{fontSize:15,fontWeight:'750',color:'#344054',flex:1,paddingRight:12},choiceTextSelected:{color:'#1254b5'},radio:{width:21,height:21,borderRadius:11,borderWidth:2,borderColor:'#aab2c0',alignItems:'center',justifyContent:'center'},radioSelected:{borderColor:palette.blue},radioDot:{width:10,height:10,borderRadius:5,backgroundColor:palette.blue},disabled:{opacity:.42},pressed:{transform:[{scale:.995}],opacity:.9},primary:{minHeight:60,borderRadius:16,backgroundColor:palette.ink,alignItems:'center',justifyContent:'center',paddingHorizontal:20,shadowColor:'#0b1220',shadowOpacity:.12,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:2},primaryDisabled:{opacity:.4,shadowOpacity:0},primaryPressed:{transform:[{scale:.995}]},primaryText:{color:'#fff',fontSize:14,fontWeight:'900',letterSpacing:.8}});