import { supabase } from '@/lib/supabase';

export type SafetyStatus = 'safe' | 'conditional' | 'not_cleared' | 'unsafe' | 'unknown';
export type QuickCheckItem = { id: string; model_name?: string | null; model_number?: string | null; manufacturer_name?: string | null; device_type?: string | null; component_type?: string | null; system_type?: string | null; required_lead_count?: number | null; slot?: string | null; [key: string]: unknown };
export type ExactComponentSelection = { slot: string; component_id: string };
export type SystemRequirement = QuickCheckItem & { status?: string | null; system_type?: string | null; required_lead_count?: number | null };
export type ConditionChecklistItem = { key: string; label: string; requirement: string; confirmed?: boolean };
export type QuickCheckResult = { version?: string; check_id?: string; checked_at?: string; status: SafetyStatus; display_status: string; safe_to_scan: boolean; conditions_met?: boolean; hard_conflict?: boolean; condition_confirmation_required?: boolean; condition_checklist?: ConditionChecklistItem[]; unconfirmed_conditions?: ConditionChecklistItem[]; requires_review: boolean; reason?: string | null; decision?: string | null; device?: Record<string, unknown> | null; component?: Record<string, unknown> | null; components?: Record<string, unknown>[]; scanner?: Record<string, unknown> | null; condition?: Record<string, unknown> | null; next_action?: string | null; [key: string]: unknown };

export async function searchDevices(search: string) { const { data, error } = await supabase.rpc('quickcheck_search_devices', { p_search: search }); if (error) throw error; return (data ?? []) as QuickCheckItem[]; }
export async function searchComponents(deviceId: string, search = '') { const { data, error } = await supabase.rpc('quickcheck_search_components', { p_device_id: deviceId, p_search: search }); if (error) throw error; return (data ?? []) as QuickCheckItem[]; }
export async function searchScanners(manufacturerId?: string) { const { data, error } = await supabase.rpc('quickcheck_search_scanners', { p_manufacturer_id: manufacturerId ?? null }); if (error) throw error; return (data ?? []) as QuickCheckItem[]; }
export async function getScannerOptions() { const { data, error } = await supabase.rpc('quickcheck_scanner_options'); if (error) throw error; return (data ?? []) as QuickCheckItem[]; }
export async function getSystemRequirements(deviceId: string) { const { data, error } = await supabase.rpc('quickcheck_get_system_requirements', { p_device_id: deviceId }); if (error) throw error; return (data ?? []) as SystemRequirement[]; }
export async function runQuickCheck(input: { device_id: string; component_id?: string; scanner_model_id?: string; scanner_strength_t: number; scan_region: string }) { const { data, error } = await supabase.functions.invoke('quickcheck', { body: input }); if (error) throw error; return data as QuickCheckResult; }
export async function runExactSystemQuickCheck(input: { device_id: string; components: ExactComponentSelection[]; scanner_model_id: string; scanner_strength_t: number; scan_region: string }) { const { data, error } = await supabase.rpc('quickcheck_run_exact_system_check_v2', { p_device_id: input.device_id, p_components: input.components, p_scanner_model_id: input.scanner_model_id, p_scanner_strength_t: input.scanner_strength_t, p_scan_region: input.scan_region }); if (error) throw error; return data as QuickCheckResult; }
export async function finalizeConditionCheck(checkId: string, confirmations: Record<string, boolean>) { const { data, error } = await supabase.rpc('quickcheck_finalize_condition_check', { p_check_id: checkId, p_confirmations: confirmations }); if (error) throw error; return data as QuickCheckResult; }
